### ISSUE TITLE
WebSocket disconnection after background for some time

### ISSUE THREAD

**Issue by Sleechigo** [reown-com/reown_flutter#23] opened 2024-10-18 16:38 UTC
Hi, I noticed that automatic reconnection after closing app or refreshing the state is not that effective. For trust wallet connection, it takes a little time to reconnect when you come back to the app, but for metamask and exodus wallet, it hardly reconnects. I've tested this in 4 different andriod devices and 2 ios. Also, metamask hardly connects using the wallet icon interface, but for qrcode, it connects perfectly.
Please if you'd update the persistent session or automatic reconection, it would be highly appreciated. Also if you can add support for formatting bigint and ethers conversion of units, that would go a long way. Outside these, Reown works perfectly fine and better with the [1.1.0-beta02] release.

**Comment by AliAzizi** [comment] 2024-10-18 20:44
I am experiencing the same issue. When the Flutter app goes into the background (onPause), and we send a request to connect to MetaMask, it seems that the WebSocket connection (relay) disconnects automatically after a few seconds. This prevents the request from completing successfully.

For instance, when trying to connect our dapp to MetaMask, we initiate the connection request, and MetaMask opens as expected. However, since the user needs to wait for the "Approve" button to appear, the WebSocket may disconnect during this wait time. Once the user hits "Approve" and returns to the Flutter dApp, the app does nothing and shows a "Try Again" button. This issue occurs about 90% of the time.

**Comment by quetool** [comment] 2024-10-23 11:57
Thanks both for the reports, I'll be taking a look at them. I understand @AliAzizi report but not so much your's @Sleechigo... If you could both share a demo video I'd highly appreciate as we had never been reported of such issues.

**Comment by quetool** [comment] 2024-10-23 12:01
As per the WebSocket disconnection I'm lost there as disconnection shouldn't happen that quick and, in fact, I can't reproduce it even with the link conditioner set to High Latency so I might need some more help discovering the issue.

**Comment by xdkomel** [comment] 2024-11-15 20:29
@quetool Hello! I have experienced a similar problem when testing the SDK. The way @AliAzizi describes it, when the app is in background the relay disconnects. 

I could reproduce the bug in the example appkit project `reown_flutter/packages/reown_appkit/example/base`. However, to start the project I needed to add this to the `pubspec.yaml` since the pinenacl 0.5.1 refused to wotk as is:
```
dependency_overrides:
  pinenacl: 0.6.0
```

Here is the log: https://pastecode.io/s/pbja4s1a
Here is the screencast: https://disk.yandex.ru/i/uSaOlzrlT1Ri6w. Ran it on OnePlus 5T, Android 15

**Comment by haykgalstyan** [comment] 2024-11-30 08:19
Any news on this? Currently we don't have a working android version of the sdk as I understand?

**Comment by quetool** [comment] 2024-12-03 11:05
Can you all confirm that is happening only on Android @AliAzizi @Sleechigo @xdkomel @haykgalstyan ?

Some more details you can share? 
Device model?
Type of connection?
Android version?
Are you running the example/base folder or directly trying the SDK as dependency? If the latter, which version?

**Comment by haykgalstyan** [comment] 2024-12-03 11:56
> I am experiencing the same issue. When the Flutter app goes into the background (onPause), and we send a request to connect to MetaMask, it seems that the WebSocket connection (relay) disconnects automatically after a few seconds. This prevents the request from completing successfully.
> 
> For instance, when trying to connect our dapp to MetaMask, we initiate the connection request, and MetaMask opens as expected. However, since the user needs to wait for the "Approve" button to appear, the WebSocket may disconnect during this wait time. Once the user hits "Approve" and returns to the Flutter dApp, the app does nothing and shows a "Try Again" button. This issue occurs about 90% of the time.
> 
> `Closed by client with code 1006 .`

This comment perfectly describes my issue. 
Maybe something tied to android lifecycle and pausing of the connection.
My device is a pixel8 updated to the latest version of android. 
I use it as a dependency, It worked for a long time, then suddenly stopped some time after Reown migration.

I dont use SIWE if this helps reproduce the issue. Just basic connecting to wallet.

Here's my initialization code if it could help

`
appkit.ReownAppKitModal _createModalService(UiContext context) {
    return appkit.ReownAppKitModal(
      context: context.as<BuildContext>(),
      projectId: _config.projectId,
      metadata: appkit.PairingMetadata(
        name: _config.appInfo.name,
        description: _config.appInfo.description,
        url: _config.appInfo.url,
        icons: [_config.appInfo.iconUrl],
        redirect: appkit.Redirect(
          native: _config.appInfo.redirectNativeScheme,
        ),
      ),
      requiredNamespaces: {
        'eip155': appkit.RequiredNamespace(
          chains: _config.requiredChains,
          methods: _config.requiredMethods,
          events: _config.requiredEvents,
        ),
      },
      enableAnalytics: false,
      logLevel: _loggingEnabled ? appkit.LogLevel.all : appkit.LogLevel.nothing,
    );
  }`

**Comment by quetool** [comment] 2024-12-03 16:12
Seems to be different reasons of closing the connection, @xdkomel is getting 1002 while the others are getting 1006. I'll investigate and update this thread. @haykgalstyan do you remember last time/version that it used to work?

**Comment by haykgalstyan** [comment] 2024-12-04 09:04
I don't remember, but I can do the testing if that will help us solve this @quetool.

**Comment by raegartargarian** [comment] 2024-12-12 13:43
Hi.
this issue is happening for us on android 15 only, on other android versions it works fine. we get this error on android 15:
connection [ReownAppKitModal] relay client error: WebSocketChannelException: SocketException: Failed host lookup: 'relay.walletconnect.org' (OS Error: No address associated with hostname, errno = 7) @quetool

**Comment by quetool** [comment] 2024-12-12 14:25
Interesting... Thank you @raegartargarian! And thanks everyone else for the patience, we are still looking at the actual reasons on this issue!

**Comment by haykgalstyan** [comment] 2024-12-12 16:00
My android version is also 15. So this will help you reproduce most probably @quetool

**Comment by quetool** [comment] 2024-12-16 09:17
Thank you all! We are going to take a look at this consistently this week.
What we are going to do:

1. Update our SDK to be fully compatible with latest Flutter version
2. Update every dependency
3. Remove/revisit connectivity checker (it might be giving some troubles.
4. Deploy a beta release with these changes and let you test it out.

Wait more news soon.

**Comment by quetool** [comment] 2024-12-16 18:12
Hello @haykgalstyan @xdkomel @raegartargarian @AliAzizi @Sleechigo 

I have been debugging this for a few hours and this is a summary of my founding: https://github.com/dart-lang/web_socket_channel/issues/279#issuecomment-2546313396

This issue escalated our priority list now. I will keep posting here but if you have any more insights please let me know.

**Comment by quetool** [comment] 2024-12-18 14:25
I'm glad to announce that we are about to fix this annoying issue affecting Android 15. A new beta is going to be released soon!

**Closed** 2024-12-18 17:26 UTC
Labels: investigation, dependencies

**Comment by quetool** [comment] 2024-12-18 19:09
Hello @haykgalstyan @xdkomel @raegartargarian @AliAzizi @Sleechigo !

New beta version with this issue fixed is published! 

AppKit: https://pub.dev/packages/reown_appkit/versions/1.3.0-beta01/changelog
WalletKit: https://pub.dev/packages/reown_walletkit/versions/1.1.0-beta01/changelog

Please test them out and let me know!

**Comment by quetool** [comment] 2024-12-30 09:43
Hello everyone! Reaching out to check if the issue with reconnection is finally fixed on latest beta.

**Comment by haykgalstyan** [comment] 2024-12-30 09:53
Well, it's better no doubt, but to me still finicky. I still see disconnection errors and have a pretty high chance of wallet connection or other wallet interactions not succeeding...

Here's a snippet from the logs:

`13:45:35.880  I  2024-12-30 13:45:35.879972 🐛 [RelayClient]: Handling relay close, code: 1002, reason: 
13:45:35.881  I  2024-12-30 13:45:35.881577 🐛 [RelayClient]: _connect null, isConnected: false
13:45:35.883  I  2024-12-30 13:45:35.883470 📝 [RelayClient] Connecting to relay url wss://relay.walletconnect.org
13:45:35.884  I  2024-12-30 13:45:35.884052 🐛 [RelayClient]: _disconnecting from relay
13:45:36.012  I  2024-12-30 13:45:36.011776 🐛 [RelayClient]: Signed JWT: eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6a2V5Ono2TWtzRWI5Vmp1QUM4QVZqTHpYbWZGSzdWUkFnZHpjeFl1Z256eEU3WE1NSGlDRyIsInN1YiI6IjA5ZjdhMTIzZWY1ZmI2ZmZlMTY1MjdhMmFhNDg2YzZiZDY2NmVkYjBlMzMzN2FhNDRmOGI5MzYzOWNlNzAyNTAiLCJhdWQiOiJ3c3M6Ly9yZWxheS53YWxsZXRjb25uZWN0Lm9yZyIsImlhdCI6MTczNTU1MTg3NSwiZXhwIjoxNzM1NjM4Mjc1fQ.PB16x1P6CYXOZO92qfsIVPz9_p0GKDC99cG_qCxv5ZqTFlBOEk4u9zdNowRekDyaXc45sT8YAamJZW8A7hsSDw
13:45:36.013  I  2024-12-30 13:45:36.013437 🐛 [RelayClient]: Initializing WebSocket with wss://relay.walletconnect.org?auth=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6a2V5Ono2TWtzRWI5Vmp1QUM4QVZqTHpYbWZGSzdWUkFnZHpjeFl1Z256eEU3WE1NSGlDRyIsInN1YiI6IjA5ZjdhMTIzZWY1ZmI2ZmZlMTY1MjdhMmFhNDg2YzZiZDY2NmVkYjBlMzMzN2FhNDRmOGI5MzYzOWNlNzAyNTAiLCJhdWQiOiJ3c3M6Ly9yZWxheS53YWxsZXRjb25uZWN0Lm9yZyIsImlhdCI6MTczNTU1MTg3NSwiZXhwIjoxNzM1NjM4Mjc1fQ.PB16x1P6CYXOZO92qfsIVPz9_p0GKDC99cG_qCxv5ZqTFlBOEk4u9zdNowRekDyaXc45sT8YAamJZW8A7hsSDw&ua=wc-2%2FReown-Flutter-1.1.0-beta02%2Fandroid-AP4A.241205.013%2Fandroid&projectId=daf7b60814b655a2a42990bcf38eea05&packageName=com.makeyourcoin.app
13:45:36.033  I  2024-12-30 13:45:36.032959 ❌ [RelayClient], _connect error: WebSocketChannelException: SocketException: Failed host lookup: 'relay.walletconnect.org' (OS Error: No address associated with hostname, errno = 7)
13:45:36.034  I  2024-12-30 13:45:36.033697 📝 [ReownAppKitModal] relay client error: WebSocketChannelException: SocketException: Failed host lookup: 'relay.walletconnect.org' (OS Error: No address associated with hostname, errno = 7)`

**Comment by quetool** [comment] 2024-12-30 10:26
Are you telling that you are still facing unsuccessful connections with the wallet?
Failing logs has been left there on purpose since this disconnecting behavior will always happen on Android 15 (I could remove the logs in the future). The important thing is that relay gets reconnected after this happens. You shouldn't have unsuccessful connections or interactions with the wallet even if you see the log in the console.
