### ISSUE TITLE
Issue with session persistence

### ISSUE THREAD

**Issue by AndriiVivcharenko** [reown-com/reown_flutter#12] opened 2024-10-09 12:50 UTC
I'm not sure if this is a bug or if I just missed something. I've been debugging this issue for a while now.

Context: we just [upgraded](https://docs.reown.com/appkit/upgrade/from-web3modal-flutter) the package from [`web3modal_flutter`](https://github.com/WalletConnect/Web3ModalFlutter) to `reown_flutter`. We didn't change anything except for new class names, imports, parameters, etc.

Overall everything is working fine, but we just found out that the session is not persistent. 
I'm not familiar with the codebase, but this is what I've been able to figure out.
When the [restore() method](https://github.com/reown-com/reown_flutter/blob/83b1a181e6198ffa19971296106c036a4574b926/packages/reown_core/lib/store/generic_store.dart#L132) is called in the [`GenericStore`](https://github.com/reown-com/reown_flutter/blob/develop/packages/reown_core/lib/store/generic_store.dart) class for the `sessions` context, it tries to access the `wc@2:core:sessions` key, while the actual session is stored with the version in that key. I've attached a screenshot from the debugger where you can see that I have a session in the shared prefs with the key `wc@2:core:1.1//sessions`, but it is looking for `wc@2:core:sessions`
![Pasted Graphic](https://github.com/user-attachments/assets/1545fda1-ea93-420c-b2d5-94e2cbdbac49)

I would appreciate any help in further debugging this issue. Thanks

**Comment by quetool** [comment] 2024-10-11 13:23
Thank you @AndriiVivcharenko I'll be investigating!

**Comment by quetool** [comment] 2024-10-17 15:36
Hello @AndriiVivcharenko ! I still can not reproduce this issue on my side, any chance you can share a complete example to reproduce it?

**Comment by quetool** [comment] 2024-10-29 09:10
Hello @AndriiVivcharenko ! This is going to be fixed in next release! Thanks for the report!

**Comment by AndriiVivcharenko** [comment] 2024-11-01 13:41
> Hello @AndriiVivcharenko ! This is going to be fixed in next release! Thanks for the report!

Hi @quetool, sorry for my delayed response. We did not have enough time to investigate this issue in more detail
I just tried to quickly test it with the `develop` branch, but it still doesn't work for me. I tried to pull a minimal sample code into this repository https://github.com/AndriiVivcharenko/reown_repro

I also added a screen recording where I do a hot restart after connecting my trust wallet and the button changes its state back to “Connect wallet”.

**Comment by quetool** [comment] 2024-11-01 13:48
Thanks @AndriiVivcharenko! Which version of AppKit are you using currently?

**Comment by quetool** [comment] 2024-11-01 14:04
Hello @AndriiVivcharenko! I just tried your code and removed every piece of code where you handle the session yourself and it works perfectly as expected. This is clearly not an issue on our side, rather on your code/implementation. You shouldn't handle the storage of the session yourself, AppKit is perfectly capable of doing it.

Here's a video demo where I connect with our sample wallet and then refresh twice. Session persists as expected. Please reorganize your code and you'll see everything works.

https://github.com/user-attachments/assets/5536dfae-4cb8-4ad7-b919-3e09a51cd7ce

Here's the modified code of your example:

```dart
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:reown_appkit/reown_appkit.dart';
import 'package:shared_preferences/shared_preferences.dart';

const WC_PROJECT_ID = 'bfc0c865817b858fabef308705f8e546';

void main() async {
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends ConsumerStatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  ConsumerState<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends ConsumerState<MyHomePage> {
  static int nowPlusThreeHours() =>
      DateTime.now()
          .add(
            const Duration(
              hours: 3,
            ),
          )
          .millisecondsSinceEpoch ~/
      1000;

  @override
  void initState() {
    super.initState();

    _setProviderStatesFromPersistedState();
  }

  Future<void> _cleanSession() async {
    print("cleaning session ${StackTrace.current}");
    // final storage = await SharedPreferences.getInstance();
    // final wcService = ref.read(w3mServiceProvider);

    // storage.remove('session');
    // storage.remove('walletType');
    // storage.remove('userSession');
    // wcService?.disconnect();
    // await BackendAuth.initGuestSession().timeout(const Duration(
    //   seconds: 8,
    // ));
  }

  Future<void> _setProviderStatesFromPersistedState() async {
    try {
      await Future.wait(
        [
          initWcClient(ref, context),
          // setupWeb3Auth(),
        ],
      );
    } catch (e, s) {
      print(e);
      print(s);
      // await Sentry.captureException(
      //   e,
      //   stackTrace: s,
      // );
      // FlutterNativeSplash.remove();
    }

    // final storage = await SharedPreferences.getInstance();

    try {
      // final wcService = ref.read(w3mServiceProvider);

      // final storedWcSession = storage.getString('session');

      //check if a session is stored
      // if (storedWcSession == null) {
      //   _cleanSession();
      //   throw Exception('No session stored');
      // }

      // final wcSession =
      //     ReownAppKitModalSession.fromMap(jsonDecode(storedWcSession));

      // if ((wcSession.expiry ?? 0) <= nowPlusThreeHours()
      //     // && backendSession.expire ?? 0 <= nowPlusThreeHours()
      //     ) {
      //   _cleanSession();
      //   throw Exception('Session expired');
      // }

      // ref.read(wcSessionProvider.notifier).state = wcSession;
      // ref.read(walletTypeProvider.notifier).state = walletType;
      // ref.read(userSessionProvider.notifier).state = backendSession;
      // Backend.recreateServices(backendSession.jwt.raw);
      // ref.read(websocketProvider.notifier).init();
    } catch (e, st) {
      // Sentry.captureException(
      //   e,
      //   stackTrace: st,
      // );
      // _cleanSession();
    } finally {
      // FlutterNativeSplash.remove();
    }
  }

  @override
  Widget build(BuildContext context) {
    // final session = ref.watch(wcSessionProvider);
    final w3mService = ref.watch(w3mServiceProvider);
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            if (w3mService != null)
              AppKitModalConnectButton(
                appKit: w3mService,
              )
          ],
        ),
      ),
    );
  }
}

final w3mServiceProvider = StateProvider<ReownAppKitModal?>((ref) {
  return null;
});

final wcSessionProvider = StateProvider<ReownAppKitModalSession?>((ref) {
  return null;
});

Future<ReownAppKitModal> initWcClient(
    WidgetRef ref, BuildContext context) async {
  //create Web3Modal service and set provider
  final ReownAppKitModal w3mService = ReownAppKitModal(
    context: context,
    projectId: WC_PROJECT_ID,
    metadata: const PairingMetadata(
        name: 'Test',
        description: 'Test - Test',
        url: 'https://www.google.com',
        icons: ['https://avatars.githubusercontent.com/u/116345848'],
        redirect: Redirect(
          native: 'io.andriivivcharenko.reown.session.reownRepro://',
        )),
  );

  w3mService.onSessionEventEvent.subscribe(wrapOnSessionEvent(ref));
  w3mService.onModalConnect.subscribe(wrapOnSessionConnect(ref, context));
  w3mService.onModalDisconnect.subscribe(wrapOnSessionDisconnect(ref));
  w3mService.onSessionExpireEvent.subscribe(wrapOnSessionExpire(ref));

  await w3mService.init();
  ref.read(w3mServiceProvider.notifier).state = w3mService;

  return w3mService;
}

void Function(ModalConnect?) wrapOnSessionConnect(
  WidgetRef ref,
  BuildContext context,
) {
  return (ModalConnect? args) {
    //set session and wallet type provider
    ref.read(wcSessionProvider.notifier).state = args?.session;

    //store session and wallet type
    // final storage = SharedPreferences.getInstance();
    // final session = jsonEncode(args?.session.toMap());
    // storage.then((s) {
    //   s.setString('session', session);
    //   print(s);
    // });
  };
}

void Function(ModalDisconnect?) wrapOnSessionDisconnect(WidgetRef ref) {
  return (ModalDisconnect? args) {
    onSessionDisconnect(args, ref);
  };
}

void Function(SessionExpire?) wrapOnSessionExpire(WidgetRef ref) {
  return (SessionExpire? event) {
    if (event?.topic != null) {
      onSessionDisconnect(
        ModalDisconnect(
          topic: event!.topic,
        ),
        ref,
      );
    }
  };
}

void Function(SessionEvent?) wrapOnSessionEvent(WidgetRef ref) {
  return (SessionEvent? args) {
    // talker.log('Session event: ${args?.chainId}');
  };
}

void onSessionDisconnect(ModalDisconnect? args, WidgetRef ref) {
  //remove session and wallet type
  // final storage = SharedPreferences.getInstance();
  // storage.then((value) => value.remove('session'));
  // storage.then((value) => value.remove('walletType'));
  // storage.then((value) => value.remove('userSession'));

  ref.read(wcSessionProvider.notifier).state = null;
}
```

**Comment by quetool** [comment] 2024-11-01 14:04
I'll close since this is not on our side.

**Closed by quetool** 2024-11-01 14:04 UTC
Labels: bug, appkit
