### ISSUE TITLE
Wallet connection not working for android at all

### ISSUE THREAD

**Issue by haykgalstyan** [reown-com/reown_flutter#48] opened 2024-11-30 08:21 UTC
I get this error every time trying to connect to a wallet on android.

❌ [RelayClient], _connect error: SocketException: Failed host lookup: 'relay.walletconnect.org' (OS Error: No address associated with hostname, errno = 7)
I/flutter (30300): 2024-11-30 12:18:05.849820 📝 [ReownAppKitModal] relay client error: SocketException: Failed host lookup: 'relay.walletconnect.org' (OS Error: No address associated with hostname, errno = 7)

**Comment by haykgalstyan** [comment] 2024-11-30 08:24
This happens when the wallet is opened and while the user authenticates and comes back the pairing does not succeed.

**Comment by haykgalstyan** [comment] 2024-11-30 08:25
We have this [related issue](https://github.com/reown-com/reown_flutter/issues/23#issuecomment-2479865591), but it seems strange that we don't have a working version of this basic functionality for such a long time.

**Comment by quetool** [comment] 2024-12-03 08:41
Are you seen this error right from the start of the app or just when coming back from the connection flow? Is this happening only on Android? Could you provide a minimum reproducible code?

**Comment by haykgalstyan** [comment] 2024-12-03 10:56
I see this error while user is connecting in the wallet, and when they are back I see failure to connect. I see this happening in android because, iOS works fine.

Before I start a project to write the reproducible code can you confirm you are not able to reproduce this? I have linked an issue where other people are having the same problem, so it should not be hard to reproduce.

**Comment by quetool** [comment] 2024-12-03 11:03
I am not able to reproduce this issue at all and it's also weird. I mean, I would expect the relay either to work or to not work at all but being able to initiate a connection but unable to finish it it's just weird. I am also following the other issue as well and tried several times and several approaches both on Android physical device and emulator. Since this issue is the same as the original one (the one you linked) let's move our discussion there so we are all updated and every part involved can give feedback. I'll close this for now, let's continue here https://github.com/reown-com/reown_flutter/issues/23. Thanks!

**Closed** 2024-12-18 17:26 UTC
Labels: duplicate
