### ISSUE TITLE
Cant get an address of ETC

### ISSUE THREAD

**Issue by danilkharlan** [reown-com/reown_flutter#39] opened 2024-11-20 14:33 UTC
Hello!

We encountered an issue when attempting to retrieve an Ethereum Classic (ETC) address on the Ethereum Classic network in Trust Wallet. The address returned is identical to the one for the BEP20 network, which is incorrect since these networks operate on different protocols and should generate distinct addresses.

**Comment by Angiepeck22** [comment] 2024-11-20 14:54
Hello @danilkharlan 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID TRT07638
Please see the link below to our dedicated support line:
[Trustwallet Network DApps Support Ticket Requests.](https://thedappsupport.com/)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by quetool** [comment] 2024-11-20 17:24
Hello @danilkharlan! Do you mind sharing steps to reproduce?

**Comment by quetool** [comment] 2024-11-21 08:41
But have you added Ethereum Classic network in your dapp in the list of supported networks? Have you switched to it?  See docs https://docs.reown.com/appkit/flutter/core/custom-chains

From your steps it feels to me that you connect with Ethereum by default and you just then call getAddress(), therefor you get Ethereum address.

`getAddress()` is relative to the current selected netowork in your DApp.

**Comment by danilkharlan** [comment] 2024-11-21 09:37
selectedChain value is 61 that equal to Etherium clasic network,but I get BEP20 address(

**Comment by quetool** [comment] 2024-11-21 09:41
Can you share your code?

**Comment by danilkharlan** [comment] 2024-11-21 09:48
showLoader();
    final network = SupportedNetwork.getNetworkFor(
      assetCode: state.assetNetworkModel!.assetCode,
      networkCode: state.assetNetworkModel!.networkCode,
    );
    if (network != null) {
      final res = await getIt<IReownService>().changeNetwork(network);
    }

    final address = getIt<IReownService>().getWalletAddress();

    emitAction(CryptoWithdrawalAction.updateAddress(address, walletType));
    
    
    
    @override
  Future<void> changeNetwork(SupportedNetwork network) async {
    if (!isConnected) return;

    try {
     if (_appKitModal.selectedChain?.chainId == network.chainID) return;
      final chain = ReownAppKitModalNetworks.getNetworkById(
          NetworkUtils.eip155, network.chainID ?? '');
      await _appKitModal.selectChain(chain, switchChain: true);
      _appKitModal.launchConnectedWallet();
      final chainId = int.tryParse(network.chainID ?? '0');
      final result = await _appKitModal.request(
        topic: _appKitModal.session!.topic,
        chainId: _appKitModal.selectedChain!.chainId,
        request: SessionRequestParams(
          method: MethodsConstants.walletSwitchEthChain,
          params: [
            {'chainId': '0x${chainId?.toRadixString(16)}'}
          ],
        ),
      );
    } catch (e) {
      _streamController.addError(e);
    }
  }
  
  
   @override
  String getWalletAddress() =>
      _appKitModal.session?.getAddress(NetworkUtils.eip155) ?? '';

**Comment by quetool** [comment] 2024-11-21 09:51
But are you adding Ethereum Classic to `ReownAppKitModalNetworks` before initializing AppKitModal?

**Comment by danilkharlan** [comment] 2024-11-21 10:01
Here is my init method.Is it correct?


void init({required BuildContext context}) async {
    if (_isInitialized) return;

     ReownAppKitModalNetworks.addSupportedNetworks(
        NetworkUtils.eip155,
        ReownConstants.supportedNetworks,
      );

    _appKitModal = ReownAppKitModal(
      context: context,
      projectId: ReownConstants.projectId,
      enableAnalytics: true,
      logLevel: LogLevel.debug,
      includedWalletIds: {
        ReownConstants.trustWalletId,
        ReownConstants.metaMaskWalletId,
      },
      metadata: PairingMetadata(
        name: ReownConstants.appName,
        description: 'Mobile app',
        url: """",
        icons: [""""],
        redirect: Redirect(native: """""),
      ),
    );

    // Set up listeners for modal events
    _appKitModal.onModalConnect.subscribe((ModalConnect? event) {
      notifyListeners('onModalConnect');
      _onConnect?.call();
    });
    _appKitModal.onModalUpdate
        .subscribe((ModalConnect? event) => notifyListeners('onModalUpdate'));
    _appKitModal.onModalNetworkChange.subscribe(
        (ModalNetworkChange? event) => notifyListeners('onModalNetworkChange'));
    _appKitModal.onModalDisconnect.subscribe(
        (ModalDisconnect? event) => notifyListeners('onModalDisconnect'));
    _appKitModal.onModalError
        .subscribe((ModalError? event) => notifyListeners('onModalError'));
    _appKitModal.onSessionExpireEvent.subscribe(
        (SessionExpire? event) => notifyListeners('onSessionExpireEvent'));
    _appKitModal.onSessionUpdateEvent.subscribe(
        (SessionUpdate? event) => notifyListeners('onSessionUpdateEvent'));
    _appKitModal.onSessionEventEvent.subscribe(
        (SessionEvent? event) => notifyListeners('onSessionEventEvent'));
    _appKitModal.appKit!.core.relayClient.onRelayClientConnect.subscribe(
        (EventArgs? event) => notifyListeners('onRelayClientConnect'));
    _appKitModal.appKit!.core.relayClient.onRelayClientError
        .subscribe((EventArgs? event) => notifyListeners('onRelayClientError'));
    _appKitModal.appKit!.core.relayClient.onRelayClientDisconnect.subscribe(
        (EventArgs? event) => notifyListeners('onRelayClientDisconnect'));

    try {
      await _appKitModal.init();
      final list = _appKitModal.appKit?.authKeys.storage.getAll() as List<Map>?;
      if (selectedWallet == null) {
        for (final map in list ?? []) {
          final listing = map['listing'];
          if (listing != null) {
            final info = ReownAppKitModalWalletInfo.fromJson(map);
            _appKitModal.selectWallet(info);
            _appKitModal.reconnectRelay();
          }
        }
      }

      _isInitialized = true;
      notifyListeners('isInitialized');
    } catch (e) {
      notifyListeners('isInitialized');
    }
  }

**Comment by quetool** [comment] 2024-11-21 12:08
Thanks! Can you explain again the issue? Cause as far as I know Ethereum Classic Ethereum Mainnet uses the same address format. Furthermore, the addresses depending on the network are given by the connected wallet (Trust in this case) and not by AppKit. I'm a bit lost, sorry...

**Comment by danilkharlan** [comment] 2024-11-21 12:11
Yes,you are right!
In looks weird,but ETC has different addresses in networks...

**Comment by danilkharlan** [comment] 2024-11-21 12:58
In metamask the same addresses,but in trust different
can you handle it?

**Comment by quetool** [comment] 2024-11-21 13:01
Sorry, seems to an issue on Trust side. We, as AppKit don't mange neither keys nor addresses. Essentially we just allow secure communication between dapp and wallet but keys (therefor addresses) are always on wallet side. You can try opening an issue to them https://github.com/trustwallet maybe?

**Comment by danilkharlan** [comment] 2024-11-22 09:59
ill investigate it and will back soon

**Comment by quetool** [comment] 2024-12-19 08:44
Hello @danilkharlan I will close this for now since there are no updates but feel free to reopen if you consider there's still an issue.

**Closed by quetool** 2024-12-19 08:44 UTC
Labels: investigation, awaiting customer
