### ISSUE TITLE
Doesn't compile without some dependency fix

### ISSUE THREAD

**Issue by rommex** [reown-com/reown_flutter#50] opened 2024-12-04 10:18 UTC
**Describe the bug**

I'm trying to compile the project clean off the repo and launch on my iPhone device.

I keep getting this error:

```
...
Xcode build done.                                           14.5s
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): ../../../../../../../.pub-cache/hosted/pub.dev/pinenacl-0.5.1/lib/api/api.dart:90:12: Error: Method not found: 'UnmodifiableUint8ListView'.
```

**To Reproduce**

1. Download the repo
2. Run on a real iOS device

**FIX**

I managed to launch the app with these fixes in the pubspec:

```
dependencies:
  pinenacl: ^0.5.1  # Try an older, more stable version
  typed_data: ^1.3.2  # or the latest version

dependency_overrides:
  typed_data: ^1.3.2
  pinenacl:
    git:
      url: https://github.com/ilap/pinenacl-dart
      ref: master  # or try 'main'
```

**Comment by quetool** [comment] 2024-12-04 11:44
Hello @rommex! This is a duplicate of this one https://github.com/reown-com/reown_flutter/issues/18#issuecomment-2450140919

Dependency updates is going to be addressed soon, however the example app is not part of the SDK per se so this is low priority. Your fix is correct.

**Closed by quetool** 2024-12-04 11:44 UTC

**Comment by quetool** [comment] 2024-12-19 08:41
Hello @rommex a new beta version is out
https://pub.dev/packages/reown_appkit/versions/1.3.0-beta01/changelog
