### ISSUE TITLE
tockepocket connect

### ISSUE THREAD

**Issue by kishanflutter** [reown-com/reown_flutter#43] opened 2024-11-22 12:53 UTC
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(ACTIVITY_NOT_FOUND, No Activity found to handle intent { tpoutside:// }, null, null)

Already mentioned this in android menifiest file

         <package android:name="vip.mytokenpocket"/>

**Comment by quetool** [comment] 2024-11-25 08:29
Thanks for opening, allow us some time to investigate.

**Comment by quetool** [comment] 2024-11-26 14:30
Hello @kishanflutter ! I'm unable to reproduce, TokenPocket is properly detected on my side. Can you confirm you see the green checkmark on it?

![Screenshot_20241126-152659](https://github.com/user-attachments/assets/ba0d8b81-f175-4eb9-a456-4e628b243f82)

**Comment by quetool** [comment] 2024-12-19 08:45
Hello @kishanflutter! I will close this for now since there are no updates but feel free to reopen if you consider there's still an issue.

**Closed by quetool** 2024-12-19 08:45 UTC
Labels: investigation, appkit, awaiting customer

**Comment by kishanflutter** [comment] 2024-12-19 10:48
Wallet Connect is working fine but when i interact approve or staking transection request to connected tokenpocket wallet at that time in my flutter app shows exception like below

Unhandled Exception: PlatformException(ACTIVITY_NOT_FOUND, No Activity found to handle intent { tpoutside:// }, null, null)

**Comment by quetool** [comment] 2024-12-19 10:58
Can you provide steps to reproduce and/or reproducible code?
