### ISSUE TITLE
Can't connect with google and facebook social networks

### ISSUE THREAD

**Issue by karthikeyan9952** [reown-com/reown_flutter#54] opened 2024-12-09 14:26 UTC
**Issues with social logins (Google and Facebook)**

At first, I was unable to select some of the AppKitSocialOption enums, as shown in the image below.
![Screenshot 2024-12-09 at 7 20 51 PM](https://github.com/user-attachments/assets/c34d23e9-6371-47d7-b7bd-3c49234f05a4)

The UI output 
![Screenshot_1733752162](https://github.com/user-attachments/assets/44939908-e674-4f30-9122-7649f5bc0f1d)

**Then, I uncommented the commented lines, as shown in the image below.**
In lib > modal > models > public > appkit_social_options.dart
from this
![Screenshot 2024-12-09 at 7 25 49 PM](https://github.com/user-attachments/assets/824df677-f791-429d-8329-7d383b539a1b)
to this
![Screenshot 2024-12-09 at 7 25 42 PM](https://github.com/user-attachments/assets/94494df0-f101-48a8-a97e-d058ebc62b01)
In lib > modal > pages > social_login_page.dart
from this
![Screenshot 2024-12-09 at 7 25 09 P
![Screenshot 2024-12-09 at 7 46 41 PM](https://github.com/user-attachments/assets/2c03717b-c242-4885-a403-0a53bf77394d)
M](https://github.com/user-attachments/assets/7ef4d063-a6ac-4c07-a70e-ecec3036b76b)
to this
![Screenshot 2024-12-09 at 7 25 17 PM](https://github.com/user-attachments/assets/4e983571-e3f7-4693-a153-d8e8865aa2e8)

Then, I used the uncommented enum values.
![Screenshot 2024-12-09 at 7 46 41 PM](https://github.com/user-attachments/assets/0c178a48-5350-49c4-9d59-934ef9f2aa97)

Now I got this UI output
![Screenshot_1733752705](https://github.com/user-attachments/assets/c9d686ce-df3d-455f-9f5a-615d86c07950)

Now, when I try to continue with Google, it gets stuck at this page after I select my Google account.
![Screenshot_1733754052](https://github.com/user-attachments/assets/df3f96af-aeff-4b3c-a63e-a0360dd82509)

Facebook also displays this error.
![Screenshot_1733754257](https://github.com/user-attachments/assets/f64b2ed2-37ad-4b97-9013-a7275a89fbab)

How can I fix this. Thanks in advance!.

**Comment by quetool** [comment] 2024-12-09 15:12
Hello! Only X, Apple, Discord and Farcaster are enabled for now. We are still working on Google and Facebook and a few more. Duplicate of: https://github.com/reown-com/reown_flutter/issues/44#issuecomment-2497230322

**Closed by quetool** 2024-12-09 15:12 UTC
